# 1.2-secret.yaml (Modified)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-postgresql
  namespace: demo-app
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/managed-by: demo-app
type: Opaque
data:
  # Base64 encoded password for 'postgres' user
  POSTGRES_PASSWORD: "cGFzc3dvcmQ=" # password (Original)
  POSTGRES_USER: "cG9zdGdyZXM=" # postgres
  POSTGRES_URL: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzLXBvc3RncmVzcWw6NTQzMi9kZW1vX2FwcF9kYg==" # postgresql://postgres:password@postgres-postgresql:5432/demo_app_db