# 2.2-statefulset.yaml (Modified from 2.2-deployment.yaml)
apiVersion: apps/v1
kind: StatefulSet # CHANGED: Deployment -> StatefulSet
metadata:
  name: postgres
  namespace: demo-app
  annotations:
      kanister.kasten.io/blueprint: postgres-non-exclusive-backup
  labels:
        app: postgres
        app.kubernetes.io/instance: postgres    
spec:
  # Database usually runs as a single replica
  replicas: 1
  serviceName: postgres-postgresql # ADDED: Required for StatefulSet and must match the Service name (2.3-svc.yaml)
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        app.kubernetes.io/instance: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        ports:
        - containerPort: 5432
        env:
        # Load sensitive data (password, user) from the Secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-postgresql
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-postgresql
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: PGDATA
          value: "/var/lib/postgresql/data/db"

        # Mount the persistent volume for data
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc # References the PVC defined in 2.1-pvc.yaml